version: '3.1'

services:
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 15672:15672
      - 5672:5672

  express_api:
    build: ./express
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - DATABASE_URL=mongodb://mongodb:27017/my_db
    ports:
      - 3000:3000

volumes:
  mongodb_data:
